apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: disk-worker
  namespace: disk
  labels:
    app.kubernetes.io/name: disk
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: disk
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: disk
      app.kubernetes.io/component: worker
