apiVersion: v1
kind: ServiceAccount
metadata:
  name: disk-runtime
  namespace: disk
  labels:
    app.kubernetes.io/name: disk
    app.kubernetes.io/part-of: disk
automountServiceAccountToken: false
