apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: disk-api
  namespace: disk
  labels:
    app.kubernetes.io/name: disk
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: disk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: disk-api
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: External
      external:
        metric:
          name: disk_hpa_api_business_requests_inflight
        target:
          type: AverageValue
          averageValue: "20"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600
      selectPolicy: Min
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
