/**
 *
 *  FileContents.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "FileContents.hpp"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::disk;

const std::string FileContents::Cols::_id = "\"id\"";
const std::string FileContents::Cols::_hash_md5 = "\"hash_md5\"";
const std::string FileContents::Cols::_hash_sha256 = "\"hash_sha256\"";
const std::string FileContents::Cols::_size = "\"size\"";
const std::string FileContents::Cols::_storage_path = "\"storage_path\"";
const std::string FileContents::Cols::_mime_type = "\"mime_type\"";
const std::string FileContents::Cols::_ref_count = "\"ref_count\"";
const std::string FileContents::Cols::_created_at = "\"created_at\"";
const std::string FileContents::primaryKeyName = "id";
const bool FileContents::hasPrimaryKey = true;
const std::string FileContents::tableName = "\"file_contents\"";

const std::vector<typename FileContents::MetaData> FileContents::metaData_ = {
    {"id", "int64_t", "bigint", 8, 1, 1, 1},
    {"hash_md5", "std::string", "character", 0, 0, 0, 1},
    {"hash_sha256", "std::string", "character", 0, 0, 0, 1},
    {"size", "int64_t", "bigint", 8, 0, 0, 1},
    {"storage_path", "std::string", "character varying", 512, 0, 0, 1},
    {"mime_type", "std::string", "character varying", 128, 0, 0, 0},
    {"ref_count", "int32_t", "integer", 4, 0, 0, 1},
    {"created_at", "::trantor::Date", "timestamp without time zone", 0, 0, 0,
     1}};
const std::string &FileContents::getColumnName(size_t index) noexcept(false) {
  assert(index < metaData_.size());
  return metaData_[index].colName_;
}
FileContents::FileContents(const Row &r, const ssize_t indexOffset) noexcept {
  if (indexOffset < 0) {
    if (!r["id"].isNull()) {
      id_ = std::make_shared<int64_t>(r["id"].as<int64_t>());
    }
    if (!r["hash_md5"].isNull()) {
      hashMd5_ = std::make_shared<std::string>(r["hash_md5"].as<std::string>());
    }
    if (!r["hash_sha256"].isNull()) {
      hashSha256_ =
          std::make_shared<std::string>(r["hash_sha256"].as<std::string>());
    }
    if (!r["size"].isNull()) {
      size_ = std::make_shared<int64_t>(r["size"].as<int64_t>());
    }
    if (!r["storage_path"].isNull()) {
      storagePath_ =
          std::make_shared<std::string>(r["storage_path"].as<std::string>());
    }
    if (!r["mime_type"].isNull()) {
      mimeType_ =
          std::make_shared<std::string>(r["mime_type"].as<std::string>());
    }
    if (!r["ref_count"].isNull()) {
      refCount_ = std::make_shared<int32_t>(r["ref_count"].as<int32_t>());
    }
    if (!r["created_at"].isNull()) {
      auto timeStr = r["created_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  } else {
    size_t offset = (size_t)indexOffset;
    if (offset + 8 > r.size()) {
      LOG_FATAL << "Invalid SQL result for this model";
      return;
    }
    size_t index;
    index = offset + 0;
    if (!r[index].isNull()) {
      id_ = std::make_shared<int64_t>(r[index].as<int64_t>());
    }
    index = offset + 1;
    if (!r[index].isNull()) {
      hashMd5_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 2;
    if (!r[index].isNull()) {
      hashSha256_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 3;
    if (!r[index].isNull()) {
      size_ = std::make_shared<int64_t>(r[index].as<int64_t>());
    }
    index = offset + 4;
    if (!r[index].isNull()) {
      storagePath_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 5;
    if (!r[index].isNull()) {
      mimeType_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 6;
    if (!r[index].isNull()) {
      refCount_ = std::make_shared<int32_t>(r[index].as<int32_t>());
    }
    index = offset + 7;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

FileContents::FileContents(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 8) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() &&
      pJson.isMember(pMasqueradingVector[0])) {
    dirtyFlag_[0] = true;
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int64_t>(
          (int64_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() &&
      pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      hashMd5_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() &&
      pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      hashSha256_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[2]].asString());
    }
  }
  if (!pMasqueradingVector[3].empty() &&
      pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      size_ = std::make_shared<int64_t>(
          (int64_t)pJson[pMasqueradingVector[3]].asInt64());
    }
  }
  if (!pMasqueradingVector[4].empty() &&
      pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      storagePath_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[4]].asString());
    }
  }
  if (!pMasqueradingVector[5].empty() &&
      pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      mimeType_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[5]].asString());
    }
  }
  if (!pMasqueradingVector[6].empty() &&
      pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      refCount_ = std::make_shared<int32_t>(
          (int32_t)pJson[pMasqueradingVector[6]].asInt64());
    }
  }
  if (!pMasqueradingVector[7].empty() &&
      pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[7]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

FileContents::FileContents(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    dirtyFlag_[0] = true;
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("hash_md5")) {
    dirtyFlag_[1] = true;
    if (!pJson["hash_md5"].isNull()) {
      hashMd5_ = std::make_shared<std::string>(pJson["hash_md5"].asString());
    }
  }
  if (pJson.isMember("hash_sha256")) {
    dirtyFlag_[2] = true;
    if (!pJson["hash_sha256"].isNull()) {
      hashSha256_ =
          std::make_shared<std::string>(pJson["hash_sha256"].asString());
    }
  }
  if (pJson.isMember("size")) {
    dirtyFlag_[3] = true;
    if (!pJson["size"].isNull()) {
      size_ = std::make_shared<int64_t>((int64_t)pJson["size"].asInt64());
    }
  }
  if (pJson.isMember("storage_path")) {
    dirtyFlag_[4] = true;
    if (!pJson["storage_path"].isNull()) {
      storagePath_ =
          std::make_shared<std::string>(pJson["storage_path"].asString());
    }
  }
  if (pJson.isMember("mime_type")) {
    dirtyFlag_[5] = true;
    if (!pJson["mime_type"].isNull()) {
      mimeType_ = std::make_shared<std::string>(pJson["mime_type"].asString());
    }
  }
  if (pJson.isMember("ref_count")) {
    dirtyFlag_[6] = true;
    if (!pJson["ref_count"].isNull()) {
      refCount_ =
          std::make_shared<int32_t>((int32_t)pJson["ref_count"].asInt64());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[7] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void FileContents::updateByMasqueradedJson(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 8) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() &&
      pJson.isMember(pMasqueradingVector[0])) {
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int64_t>(
          (int64_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() &&
      pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      hashMd5_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() &&
      pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      hashSha256_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[2]].asString());
    }
  }
  if (!pMasqueradingVector[3].empty() &&
      pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      size_ = std::make_shared<int64_t>(
          (int64_t)pJson[pMasqueradingVector[3]].asInt64());
    }
  }
  if (!pMasqueradingVector[4].empty() &&
      pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      storagePath_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[4]].asString());
    }
  }
  if (!pMasqueradingVector[5].empty() &&
      pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      mimeType_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[5]].asString());
    }
  }
  if (!pMasqueradingVector[6].empty() &&
      pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      refCount_ = std::make_shared<int32_t>(
          (int32_t)pJson[pMasqueradingVector[6]].asInt64());
    }
  }
  if (!pMasqueradingVector[7].empty() &&
      pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[7]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void FileContents::updateByJson(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("hash_md5")) {
    dirtyFlag_[1] = true;
    if (!pJson["hash_md5"].isNull()) {
      hashMd5_ = std::make_shared<std::string>(pJson["hash_md5"].asString());
    }
  }
  if (pJson.isMember("hash_sha256")) {
    dirtyFlag_[2] = true;
    if (!pJson["hash_sha256"].isNull()) {
      hashSha256_ =
          std::make_shared<std::string>(pJson["hash_sha256"].asString());
    }
  }
  if (pJson.isMember("size")) {
    dirtyFlag_[3] = true;
    if (!pJson["size"].isNull()) {
      size_ = std::make_shared<int64_t>((int64_t)pJson["size"].asInt64());
    }
  }
  if (pJson.isMember("storage_path")) {
    dirtyFlag_[4] = true;
    if (!pJson["storage_path"].isNull()) {
      storagePath_ =
          std::make_shared<std::string>(pJson["storage_path"].asString());
    }
  }
  if (pJson.isMember("mime_type")) {
    dirtyFlag_[5] = true;
    if (!pJson["mime_type"].isNull()) {
      mimeType_ = std::make_shared<std::string>(pJson["mime_type"].asString());
    }
  }
  if (pJson.isMember("ref_count")) {
    dirtyFlag_[6] = true;
    if (!pJson["ref_count"].isNull()) {
      refCount_ =
          std::make_shared<int32_t>((int32_t)pJson["ref_count"].asInt64());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[7] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

const int64_t &FileContents::getValueOfId() const noexcept {
  static const int64_t defaultValue = int64_t();
  if (id_)
    return *id_;
  return defaultValue;
}
const std::shared_ptr<int64_t> &FileContents::getId() const noexcept {
  return id_;
}
void FileContents::setId(const int64_t &pId) noexcept {
  id_ = std::make_shared<int64_t>(pId);
  dirtyFlag_[0] = true;
}
const typename FileContents::PrimaryKeyType &
FileContents::getPrimaryKey() const {
  assert(id_);
  return *id_;
}

const std::string &FileContents::getValueOfHashMd5() const noexcept {
  static const std::string defaultValue = std::string();
  if (hashMd5_)
    return *hashMd5_;
  return defaultValue;
}
const std::shared_ptr<std::string> &FileContents::getHashMd5() const noexcept {
  return hashMd5_;
}
void FileContents::setHashMd5(const std::string &pHashMd5) noexcept {
  hashMd5_ = std::make_shared<std::string>(pHashMd5);
  dirtyFlag_[1] = true;
}
void FileContents::setHashMd5(std::string &&pHashMd5) noexcept {
  hashMd5_ = std::make_shared<std::string>(std::move(pHashMd5));
  dirtyFlag_[1] = true;
}

const std::string &FileContents::getValueOfHashSha256() const noexcept {
  static const std::string defaultValue = std::string();
  if (hashSha256_)
    return *hashSha256_;
  return defaultValue;
}
const std::shared_ptr<std::string> &
FileContents::getHashSha256() const noexcept {
  return hashSha256_;
}
void FileContents::setHashSha256(const std::string &pHashSha256) noexcept {
  hashSha256_ = std::make_shared<std::string>(pHashSha256);
  dirtyFlag_[2] = true;
}
void FileContents::setHashSha256(std::string &&pHashSha256) noexcept {
  hashSha256_ = std::make_shared<std::string>(std::move(pHashSha256));
  dirtyFlag_[2] = true;
}

const int64_t &FileContents::getValueOfSize() const noexcept {
  static const int64_t defaultValue = int64_t();
  if (size_)
    return *size_;
  return defaultValue;
}
const std::shared_ptr<int64_t> &FileContents::getSize() const noexcept {
  return size_;
}
void FileContents::setSize(const int64_t &pSize) noexcept {
  size_ = std::make_shared<int64_t>(pSize);
  dirtyFlag_[3] = true;
}

const std::string &FileContents::getValueOfStoragePath() const noexcept {
  static const std::string defaultValue = std::string();
  if (storagePath_)
    return *storagePath_;
  return defaultValue;
}
const std::shared_ptr<std::string> &
FileContents::getStoragePath() const noexcept {
  return storagePath_;
}
void FileContents::setStoragePath(const std::string &pStoragePath) noexcept {
  storagePath_ = std::make_shared<std::string>(pStoragePath);
  dirtyFlag_[4] = true;
}
void FileContents::setStoragePath(std::string &&pStoragePath) noexcept {
  storagePath_ = std::make_shared<std::string>(std::move(pStoragePath));
  dirtyFlag_[4] = true;
}

const std::string &FileContents::getValueOfMimeType() const noexcept {
  static const std::string defaultValue = std::string();
  if (mimeType_)
    return *mimeType_;
  return defaultValue;
}
const std::shared_ptr<std::string> &FileContents::getMimeType() const noexcept {
  return mimeType_;
}
void FileContents::setMimeType(const std::string &pMimeType) noexcept {
  mimeType_ = std::make_shared<std::string>(pMimeType);
  dirtyFlag_[5] = true;
}
void FileContents::setMimeType(std::string &&pMimeType) noexcept {
  mimeType_ = std::make_shared<std::string>(std::move(pMimeType));
  dirtyFlag_[5] = true;
}
void FileContents::setMimeTypeToNull() noexcept {
  mimeType_.reset();
  dirtyFlag_[5] = true;
}

const int32_t &FileContents::getValueOfRefCount() const noexcept {
  static const int32_t defaultValue = int32_t();
  if (refCount_)
    return *refCount_;
  return defaultValue;
}
const std::shared_ptr<int32_t> &FileContents::getRefCount() const noexcept {
  return refCount_;
}
void FileContents::setRefCount(const int32_t &pRefCount) noexcept {
  refCount_ = std::make_shared<int32_t>(pRefCount);
  dirtyFlag_[6] = true;
}

const ::trantor::Date &FileContents::getValueOfCreatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (createdAt_)
    return *createdAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &
FileContents::getCreatedAt() const noexcept {
  return createdAt_;
}
void FileContents::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept {
  createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
  dirtyFlag_[7] = true;
}

void FileContents::updateId(const uint64_t id) {}

const std::vector<std::string> &FileContents::insertColumns() noexcept {
  static const std::vector<std::string> inCols = {
      "hash_md5",  "hash_sha256", "size",      "storage_path",
      "mime_type", "ref_count",   "created_at"};
  return inCols;
}

void FileContents::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getHashMd5()) {
      binder << getValueOfHashMd5();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getHashSha256()) {
      binder << getValueOfHashSha256();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getSize()) {
      binder << getValueOfSize();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getStoragePath()) {
      binder << getValueOfStoragePath();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getMimeType()) {
      binder << getValueOfMimeType();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getRefCount()) {
      binder << getValueOfRefCount();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
}

const std::vector<std::string> FileContents::updateColumns() const {
  std::vector<std::string> ret;
  if (dirtyFlag_[1]) {
    ret.push_back(getColumnName(1));
  }
  if (dirtyFlag_[2]) {
    ret.push_back(getColumnName(2));
  }
  if (dirtyFlag_[3]) {
    ret.push_back(getColumnName(3));
  }
  if (dirtyFlag_[4]) {
    ret.push_back(getColumnName(4));
  }
  if (dirtyFlag_[5]) {
    ret.push_back(getColumnName(5));
  }
  if (dirtyFlag_[6]) {
    ret.push_back(getColumnName(6));
  }
  if (dirtyFlag_[7]) {
    ret.push_back(getColumnName(7));
  }
  return ret;
}

void FileContents::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getHashMd5()) {
      binder << getValueOfHashMd5();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getHashSha256()) {
      binder << getValueOfHashSha256();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getSize()) {
      binder << getValueOfSize();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getStoragePath()) {
      binder << getValueOfStoragePath();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getMimeType()) {
      binder << getValueOfMimeType();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getRefCount()) {
      binder << getValueOfRefCount();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
}
Json::Value FileContents::toJson() const {
  Json::Value ret;
  if (getId()) {
    ret["id"] = (Json::Int64)getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getHashMd5()) {
    ret["hash_md5"] = getValueOfHashMd5();
  } else {
    ret["hash_md5"] = Json::Value();
  }
  if (getHashSha256()) {
    ret["hash_sha256"] = getValueOfHashSha256();
  } else {
    ret["hash_sha256"] = Json::Value();
  }
  if (getSize()) {
    ret["size"] = (Json::Int64)getValueOfSize();
  } else {
    ret["size"] = Json::Value();
  }
  if (getStoragePath()) {
    ret["storage_path"] = getValueOfStoragePath();
  } else {
    ret["storage_path"] = Json::Value();
  }
  if (getMimeType()) {
    ret["mime_type"] = getValueOfMimeType();
  } else {
    ret["mime_type"] = Json::Value();
  }
  if (getRefCount()) {
    ret["ref_count"] = getValueOfRefCount();
  } else {
    ret["ref_count"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  return ret;
}

Json::Value FileContents::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const {
  Json::Value ret;
  if (pMasqueradingVector.size() == 8) {
    if (!pMasqueradingVector[0].empty()) {
      if (getId()) {
        ret[pMasqueradingVector[0]] = (Json::Int64)getValueOfId();
      } else {
        ret[pMasqueradingVector[0]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (getHashMd5()) {
        ret[pMasqueradingVector[1]] = getValueOfHashMd5();
      } else {
        ret[pMasqueradingVector[1]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (getHashSha256()) {
        ret[pMasqueradingVector[2]] = getValueOfHashSha256();
      } else {
        ret[pMasqueradingVector[2]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (getSize()) {
        ret[pMasqueradingVector[3]] = (Json::Int64)getValueOfSize();
      } else {
        ret[pMasqueradingVector[3]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (getStoragePath()) {
        ret[pMasqueradingVector[4]] = getValueOfStoragePath();
      } else {
        ret[pMasqueradingVector[4]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (getMimeType()) {
        ret[pMasqueradingVector[5]] = getValueOfMimeType();
      } else {
        ret[pMasqueradingVector[5]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (getRefCount()) {
        ret[pMasqueradingVector[6]] = getValueOfRefCount();
      } else {
        ret[pMasqueradingVector[6]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (getCreatedAt()) {
        ret[pMasqueradingVector[7]] = getCreatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[7]] = Json::Value();
      }
    }
    return ret;
  }
  LOG_ERROR << "Masquerade failed";
  if (getId()) {
    ret["id"] = (Json::Int64)getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getHashMd5()) {
    ret["hash_md5"] = getValueOfHashMd5();
  } else {
    ret["hash_md5"] = Json::Value();
  }
  if (getHashSha256()) {
    ret["hash_sha256"] = getValueOfHashSha256();
  } else {
    ret["hash_sha256"] = Json::Value();
  }
  if (getSize()) {
    ret["size"] = (Json::Int64)getValueOfSize();
  } else {
    ret["size"] = Json::Value();
  }
  if (getStoragePath()) {
    ret["storage_path"] = getValueOfStoragePath();
  } else {
    ret["storage_path"] = Json::Value();
  }
  if (getMimeType()) {
    ret["mime_type"] = getValueOfMimeType();
  } else {
    ret["mime_type"] = Json::Value();
  }
  if (getRefCount()) {
    ret["ref_count"] = getValueOfRefCount();
  } else {
    ret["ref_count"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  return ret;
}

bool FileContents::validateJsonForCreation(const Json::Value &pJson,
                                           std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, true))
      return false;
  }
  if (pJson.isMember("hash_md5")) {
    if (!validJsonOfField(1, "hash_md5", pJson["hash_md5"], err, true))
      return false;
  } else {
    err = "The hash_md5 column cannot be null";
    return false;
  }
  if (pJson.isMember("hash_sha256")) {
    if (!validJsonOfField(2, "hash_sha256", pJson["hash_sha256"], err, true))
      return false;
  } else {
    err = "The hash_sha256 column cannot be null";
    return false;
  }
  if (pJson.isMember("size")) {
    if (!validJsonOfField(3, "size", pJson["size"], err, true))
      return false;
  } else {
    err = "The size column cannot be null";
    return false;
  }
  if (pJson.isMember("storage_path")) {
    if (!validJsonOfField(4, "storage_path", pJson["storage_path"], err, true))
      return false;
  } else {
    err = "The storage_path column cannot be null";
    return false;
  }
  if (pJson.isMember("mime_type")) {
    if (!validJsonOfField(5, "mime_type", pJson["mime_type"], err, true))
      return false;
  }
  if (pJson.isMember("ref_count")) {
    if (!validJsonOfField(6, "ref_count", pJson["ref_count"], err, true))
      return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(7, "created_at", pJson["created_at"], err, true))
      return false;
  }
  return true;
}
bool FileContents::validateMasqueradedJsonForCreation(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector, std::string &err) {
  if (pMasqueradingVector.size() != 8) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty()) {
      if (pJson.isMember(pMasqueradingVector[0])) {
        if (!validJsonOfField(0, pMasqueradingVector[0],
                              pJson[pMasqueradingVector[0]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (pJson.isMember(pMasqueradingVector[1])) {
        if (!validJsonOfField(1, pMasqueradingVector[1],
                              pJson[pMasqueradingVector[1]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[1] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (pJson.isMember(pMasqueradingVector[2])) {
        if (!validJsonOfField(2, pMasqueradingVector[2],
                              pJson[pMasqueradingVector[2]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[2] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (pJson.isMember(pMasqueradingVector[3])) {
        if (!validJsonOfField(3, pMasqueradingVector[3],
                              pJson[pMasqueradingVector[3]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[3] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (pJson.isMember(pMasqueradingVector[4])) {
        if (!validJsonOfField(4, pMasqueradingVector[4],
                              pJson[pMasqueradingVector[4]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[4] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (pJson.isMember(pMasqueradingVector[5])) {
        if (!validJsonOfField(5, pMasqueradingVector[5],
                              pJson[pMasqueradingVector[5]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (pJson.isMember(pMasqueradingVector[6])) {
        if (!validJsonOfField(6, pMasqueradingVector[6],
                              pJson[pMasqueradingVector[6]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (pJson.isMember(pMasqueradingVector[7])) {
        if (!validJsonOfField(7, pMasqueradingVector[7],
                              pJson[pMasqueradingVector[7]], err, true))
          return false;
      }
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool FileContents::validateJsonForUpdate(const Json::Value &pJson,
                                         std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, false))
      return false;
  } else {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if (pJson.isMember("hash_md5")) {
    if (!validJsonOfField(1, "hash_md5", pJson["hash_md5"], err, false))
      return false;
  }
  if (pJson.isMember("hash_sha256")) {
    if (!validJsonOfField(2, "hash_sha256", pJson["hash_sha256"], err, false))
      return false;
  }
  if (pJson.isMember("size")) {
    if (!validJsonOfField(3, "size", pJson["size"], err, false))
      return false;
  }
  if (pJson.isMember("storage_path")) {
    if (!validJsonOfField(4, "storage_path", pJson["storage_path"], err, false))
      return false;
  }
  if (pJson.isMember("mime_type")) {
    if (!validJsonOfField(5, "mime_type", pJson["mime_type"], err, false))
      return false;
  }
  if (pJson.isMember("ref_count")) {
    if (!validJsonOfField(6, "ref_count", pJson["ref_count"], err, false))
      return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(7, "created_at", pJson["created_at"], err, false))
      return false;
  }
  return true;
}
bool FileContents::validateMasqueradedJsonForUpdate(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector, std::string &err) {
  if (pMasqueradingVector.size() != 8) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty() &&
        pJson.isMember(pMasqueradingVector[0])) {
      if (!validJsonOfField(0, pMasqueradingVector[0],
                            pJson[pMasqueradingVector[0]], err, false))
        return false;
    } else {
      err =
          "The value of primary key must be set in the json object for update";
      return false;
    }
    if (!pMasqueradingVector[1].empty() &&
        pJson.isMember(pMasqueradingVector[1])) {
      if (!validJsonOfField(1, pMasqueradingVector[1],
                            pJson[pMasqueradingVector[1]], err, false))
        return false;
    }
    if (!pMasqueradingVector[2].empty() &&
        pJson.isMember(pMasqueradingVector[2])) {
      if (!validJsonOfField(2, pMasqueradingVector[2],
                            pJson[pMasqueradingVector[2]], err, false))
        return false;
    }
    if (!pMasqueradingVector[3].empty() &&
        pJson.isMember(pMasqueradingVector[3])) {
      if (!validJsonOfField(3, pMasqueradingVector[3],
                            pJson[pMasqueradingVector[3]], err, false))
        return false;
    }
    if (!pMasqueradingVector[4].empty() &&
        pJson.isMember(pMasqueradingVector[4])) {
      if (!validJsonOfField(4, pMasqueradingVector[4],
                            pJson[pMasqueradingVector[4]], err, false))
        return false;
    }
    if (!pMasqueradingVector[5].empty() &&
        pJson.isMember(pMasqueradingVector[5])) {
      if (!validJsonOfField(5, pMasqueradingVector[5],
                            pJson[pMasqueradingVector[5]], err, false))
        return false;
    }
    if (!pMasqueradingVector[6].empty() &&
        pJson.isMember(pMasqueradingVector[6])) {
      if (!validJsonOfField(6, pMasqueradingVector[6],
                            pJson[pMasqueradingVector[6]], err, false))
        return false;
    }
    if (!pMasqueradingVector[7].empty() &&
        pJson.isMember(pMasqueradingVector[7])) {
      if (!validJsonOfField(7, pMasqueradingVector[7],
                            pJson[pMasqueradingVector[7]], err, false))
        return false;
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool FileContents::validJsonOfField(size_t index, const std::string &fieldName,
                                    const Json::Value &pJson, std::string &err,
                                    bool isForCreation) {
  switch (index) {
  case 0:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (isForCreation) {
      err = "The automatic primary key cannot be set";
      return false;
    }
    if (!pJson.isInt64()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 1:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 2:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 3:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isInt64()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 4:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 512) {
      err = "String length exceeds limit for the " + fieldName +
            " field (the maximum value is 512)";
      return false;
    }

    break;
  case 5:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 128) {
      err = "String length exceeds limit for the " + fieldName +
            " field (the maximum value is 128)";
      return false;
    }

    break;
  case 6:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isInt()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 7:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  default:
    err = "Internal error in the server";
    return false;
  }
  return true;
}
