/**
 *
 *  OperationLogs.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace disk
{

class OperationLogs
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _user_id;
        static const std::string _action;
        static const std::string _target_type;
        static const std::string _target_id;
        static const std::string _target_name;
        static const std::string _details;
        static const std::string _ip_address;
        static const std::string _user_agent;
        static const std::string _created_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = uint64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit OperationLogs(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit OperationLogs(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    OperationLogs(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    OperationLogs() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const uint64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const uint64_t &pId) noexcept;

    /**  For column user_id  */
    ///Get the value of the column user_id, returns the default value if the column is null
    const uint64_t &getValueOfUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getUserId() const noexcept;
    ///Set the value of the column user_id
    void setUserId(const uint64_t &pUserId) noexcept;

    /**  For column action  */
    ///Get the value of the column action, returns the default value if the column is null
    const std::string &getValueOfAction() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAction() const noexcept;
    ///Set the value of the column action
    void setAction(const std::string &pAction) noexcept;
    void setAction(std::string &&pAction) noexcept;

    /**  For column target_type  */
    ///Get the value of the column target_type, returns the default value if the column is null
    const std::string &getValueOfTargetType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTargetType() const noexcept;
    ///Set the value of the column target_type
    void setTargetType(const std::string &pTargetType) noexcept;
    void setTargetType(std::string &&pTargetType) noexcept;
    void setTargetTypeToNull() noexcept;

    /**  For column target_id  */
    ///Get the value of the column target_id, returns the default value if the column is null
    const uint64_t &getValueOfTargetId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getTargetId() const noexcept;
    ///Set the value of the column target_id
    void setTargetId(const uint64_t &pTargetId) noexcept;
    void setTargetIdToNull() noexcept;

    /**  For column target_name  */
    ///Get the value of the column target_name, returns the default value if the column is null
    const std::string &getValueOfTargetName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTargetName() const noexcept;
    ///Set the value of the column target_name
    void setTargetName(const std::string &pTargetName) noexcept;
    void setTargetName(std::string &&pTargetName) noexcept;
    void setTargetNameToNull() noexcept;

    /**  For column details  */
    ///Get the value of the column details, returns the default value if the column is null
    const std::string &getValueOfDetails() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDetails() const noexcept;
    ///Set the value of the column details
    void setDetails(const std::string &pDetails) noexcept;
    void setDetails(std::string &&pDetails) noexcept;
    void setDetailsToNull() noexcept;

    /**  For column ip_address  */
    ///Get the value of the column ip_address, returns the default value if the column is null
    const std::string &getValueOfIpAddress() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getIpAddress() const noexcept;
    ///Set the value of the column ip_address
    void setIpAddress(const std::string &pIpAddress) noexcept;
    void setIpAddress(std::string &&pIpAddress) noexcept;

    /**  For column user_agent  */
    ///Get the value of the column user_agent, returns the default value if the column is null
    const std::string &getValueOfUserAgent() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUserAgent() const noexcept;
    ///Set the value of the column user_agent
    void setUserAgent(const std::string &pUserAgent) noexcept;
    void setUserAgent(std::string &&pUserAgent) noexcept;
    void setUserAgentToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;


    static size_t getColumnNumber() noexcept {  return 10;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<OperationLogs>;
    friend drogon::orm::BaseBuilder<OperationLogs, true, true>;
    friend drogon::orm::BaseBuilder<OperationLogs, true, false>;
    friend drogon::orm::BaseBuilder<OperationLogs, false, true>;
    friend drogon::orm::BaseBuilder<OperationLogs, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<OperationLogs>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<uint64_t> id_;
    std::shared_ptr<uint64_t> userId_;
    std::shared_ptr<std::string> action_;
    std::shared_ptr<std::string> targetType_;
    std::shared_ptr<uint64_t> targetId_;
    std::shared_ptr<std::string> targetName_;
    std::shared_ptr<std::string> details_;
    std::shared_ptr<std::string> ipAddress_;
    std::shared_ptr<std::string> userAgent_;
    std::shared_ptr<::trantor::Date> createdAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[10]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "user_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "action,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "target_type,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "target_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "target_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "details,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "ip_address,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "user_agent,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[9])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[9])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} ///< namespace disk
} ///< namespace drogon_model
