/**
 *
 *  ShareFiles.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ShareFiles.hpp"

#include <string>

#include <drogon/utils/Utilities.h>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::disk;

const std::string ShareFiles::Cols::_id = "id";
const std::string ShareFiles::Cols::_share_id = "share_id";
const std::string ShareFiles::Cols::_item_type = "item_type";
const std::string ShareFiles::Cols::_item_id = "item_id";
const std::string ShareFiles::Cols::_created_at = "created_at";
const std::string ShareFiles::primaryKeyName = "id";
const bool ShareFiles::hasPrimaryKey = true;
const std::string ShareFiles::tableName = "share_files";

const std::vector<typename ShareFiles::MetaData> ShareFiles::metaData_ = {
    {         "id",        "uint64_t",       "bigint unsigned", 8, 1, 1, 1 },
    {   "share_id",        "uint64_t",       "bigint unsigned", 8, 0, 0, 1 },
    {  "item_type",     "std::string", "enum('file','folder')", 0, 0, 0, 1 },
    {    "item_id",        "uint64_t",       "bigint unsigned", 8, 0, 0, 1 },
    { "created_at", "::trantor::Date",              "datetime", 0, 0, 0, 1 }
};

const std::string& ShareFiles::getColumnName(size_t index) noexcept(false) {
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}

ShareFiles::ShareFiles(const Row& r, const ssize_t indexOffset) noexcept {
    if (indexOffset < 0) {
        if (!r["id"].isNull()) {
            id_ = std::make_shared<uint64_t>(r["id"].as<uint64_t>());
        }
        if (!r["share_id"].isNull()) {
            shareId_ = std::make_shared<uint64_t>(r["share_id"].as<uint64_t>());
        }
        if (!r["item_type"].isNull()) {
            itemType_ = std::make_shared<std::string>(r["item_type"].as<std::string>());
        }
        if (!r["item_id"].isNull()) {
            itemId_ = std::make_shared<uint64_t>(r["item_id"].as<uint64_t>());
        }
        if (!r["created_at"].isNull()) {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    } else {
        size_t offset = (size_t)indexOffset;
        if (offset + 5 > r.size()) {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull()) {
            id_ = std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 1;
        if (!r[index].isNull()) {
            shareId_ = std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 2;
        if (!r[index].isNull()) {
            itemType_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if (!r[index].isNull()) {
            itemId_ = std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 4;
        if (!r[index].isNull()) {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

ShareFiles::ShareFiles(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 5) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            shareId_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            itemType_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            itemId_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull()) {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

ShareFiles::ShareFiles(const Json::Value& pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        dirtyFlag_[0] = true;
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
        }
    }
    if (pJson.isMember("share_id")) {
        dirtyFlag_[1] = true;
        if (!pJson["share_id"].isNull()) {
            shareId_ = std::make_shared<uint64_t>((uint64_t)pJson["share_id"].asUInt64());
        }
    }
    if (pJson.isMember("item_type")) {
        dirtyFlag_[2] = true;
        if (!pJson["item_type"].isNull()) {
            itemType_ = std::make_shared<std::string>(pJson["item_type"].asString());
        }
    }
    if (pJson.isMember("item_id")) {
        dirtyFlag_[3] = true;
        if (!pJson["item_id"].isNull()) {
            itemId_ = std::make_shared<uint64_t>((uint64_t)pJson["item_id"].asUInt64());
        }
    }
    if (pJson.isMember("created_at")) {
        dirtyFlag_[4] = true;
        if (!pJson["created_at"].isNull()) {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

void ShareFiles::updateByMasqueradedJson(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 5) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            shareId_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            itemType_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            itemId_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull()) {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

void ShareFiles::updateByJson(const Json::Value& pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
        }
    }
    if (pJson.isMember("share_id")) {
        dirtyFlag_[1] = true;
        if (!pJson["share_id"].isNull()) {
            shareId_ = std::make_shared<uint64_t>((uint64_t)pJson["share_id"].asUInt64());
        }
    }
    if (pJson.isMember("item_type")) {
        dirtyFlag_[2] = true;
        if (!pJson["item_type"].isNull()) {
            itemType_ = std::make_shared<std::string>(pJson["item_type"].asString());
        }
    }
    if (pJson.isMember("item_id")) {
        dirtyFlag_[3] = true;
        if (!pJson["item_id"].isNull()) {
            itemId_ = std::make_shared<uint64_t>((uint64_t)pJson["item_id"].asUInt64());
        }
    }
    if (pJson.isMember("created_at")) {
        dirtyFlag_[4] = true;
        if (!pJson["created_at"].isNull()) {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

const uint64_t& ShareFiles::getValueOfId() const noexcept {
    static const uint64_t defaultValue = uint64_t();
    if (id_) {
        return *id_;
    }
    return defaultValue;
}

const std::shared_ptr<uint64_t>& ShareFiles::getId() const noexcept {
    return id_;
}

void ShareFiles::setId(const uint64_t& pId) noexcept {
    id_ = std::make_shared<uint64_t>(pId);
    dirtyFlag_[0] = true;
}

const typename ShareFiles::PrimaryKeyType& ShareFiles::getPrimaryKey() const {
    assert(id_);
    return *id_;
}

const uint64_t& ShareFiles::getValueOfShareId() const noexcept {
    static const uint64_t defaultValue = uint64_t();
    if (shareId_) {
        return *shareId_;
    }
    return defaultValue;
}

const std::shared_ptr<uint64_t>& ShareFiles::getShareId() const noexcept {
    return shareId_;
}

void ShareFiles::setShareId(const uint64_t& pShareId) noexcept {
    shareId_ = std::make_shared<uint64_t>(pShareId);
    dirtyFlag_[1] = true;
}

const std::string& ShareFiles::getValueOfItemType() const noexcept {
    static const std::string defaultValue = std::string();
    if (itemType_) {
        return *itemType_;
    }
    return defaultValue;
}

const std::shared_ptr<std::string>& ShareFiles::getItemType() const noexcept {
    return itemType_;
}

void ShareFiles::setItemType(const std::string& pItemType) noexcept {
    itemType_ = std::make_shared<std::string>(pItemType);
    dirtyFlag_[2] = true;
}

void ShareFiles::setItemType(std::string&& pItemType) noexcept {
    itemType_ = std::make_shared<std::string>(std::move(pItemType));
    dirtyFlag_[2] = true;
}

const uint64_t& ShareFiles::getValueOfItemId() const noexcept {
    static const uint64_t defaultValue = uint64_t();
    if (itemId_) {
        return *itemId_;
    }
    return defaultValue;
}

const std::shared_ptr<uint64_t>& ShareFiles::getItemId() const noexcept {
    return itemId_;
}

void ShareFiles::setItemId(const uint64_t& pItemId) noexcept {
    itemId_ = std::make_shared<uint64_t>(pItemId);
    dirtyFlag_[3] = true;
}

const ::trantor::Date& ShareFiles::getValueOfCreatedAt() const noexcept {
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if (createdAt_) {
        return *createdAt_;
    }
    return defaultValue;
}

const std::shared_ptr<::trantor::Date>& ShareFiles::getCreatedAt() const noexcept {
    return createdAt_;
}

void ShareFiles::setCreatedAt(const ::trantor::Date& pCreatedAt) noexcept {
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[4] = true;
}

void ShareFiles::updateId(const uint64_t id) {
    id_ = std::make_shared<uint64_t>(id);
}

const std::vector<std::string>& ShareFiles::insertColumns() noexcept {
    static const std::vector<std::string> inCols = {
        "share_id",
        "item_type",
        "item_id",
        "created_at"
    };
    return inCols;
}

void ShareFiles::outputArgs(drogon::orm::internal::SqlBinder& binder) const {
    if (dirtyFlag_[1]) {
        if (getShareId()) {
            binder << getValueOfShareId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getItemType()) {
            binder << getValueOfItemType();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getItemId()) {
            binder << getValueOfItemId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4]) {
        if (getCreatedAt()) {
            binder << getValueOfCreatedAt();
        } else {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ShareFiles::updateColumns() const {
    std::vector<std::string> ret;
    if (dirtyFlag_[1]) {
        ret.push_back(getColumnName(1));
    }
    if (dirtyFlag_[2]) {
        ret.push_back(getColumnName(2));
    }
    if (dirtyFlag_[3]) {
        ret.push_back(getColumnName(3));
    }
    if (dirtyFlag_[4]) {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void ShareFiles::updateArgs(drogon::orm::internal::SqlBinder& binder) const {
    if (dirtyFlag_[1]) {
        if (getShareId()) {
            binder << getValueOfShareId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getItemType()) {
            binder << getValueOfItemType();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getItemId()) {
            binder << getValueOfItemId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4]) {
        if (getCreatedAt()) {
            binder << getValueOfCreatedAt();
        } else {
            binder << nullptr;
        }
    }
}

Json::Value ShareFiles::toJson() const {
    Json::Value ret;
    if (getId()) {
        ret["id"] = (Json::UInt64)getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getShareId()) {
        ret["share_id"] = (Json::UInt64)getValueOfShareId();
    } else {
        ret["share_id"] = Json::Value();
    }
    if (getItemType()) {
        ret["item_type"] = getValueOfItemType();
    } else {
        ret["item_type"] = Json::Value();
    }
    if (getItemId()) {
        ret["item_id"] = (Json::UInt64)getValueOfItemId();
    } else {
        ret["item_id"] = Json::Value();
    }
    if (getCreatedAt()) {
        ret["created_at"] = getCreatedAt()->toDbStringLocal();
    } else {
        ret["created_at"] = Json::Value();
    }
    return ret;
}

std::string ShareFiles::toString() const {
    return toJson().toStyledString();
}

Json::Value ShareFiles::toMasqueradedJson(
    const std::vector<std::string>& pMasqueradingVector
) const {
    Json::Value ret;
    if (pMasqueradingVector.size() == 5) {
        if (!pMasqueradingVector[0].empty()) {
            if (getId()) {
                ret[pMasqueradingVector[0]] = (Json::UInt64)getValueOfId();
            } else {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (getShareId()) {
                ret[pMasqueradingVector[1]] = (Json::UInt64)getValueOfShareId();
            } else {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (getItemType()) {
                ret[pMasqueradingVector[2]] = getValueOfItemType();
            } else {
                ret[pMasqueradingVector[2]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (getItemId()) {
                ret[pMasqueradingVector[3]] = (Json::UInt64)getValueOfItemId();
            } else {
                ret[pMasqueradingVector[3]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[4].empty()) {
            if (getCreatedAt()) {
                ret[pMasqueradingVector[4]] = getCreatedAt()->toDbStringLocal();
            } else {
                ret[pMasqueradingVector[4]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getId()) {
        ret["id"] = (Json::UInt64)getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getShareId()) {
        ret["share_id"] = (Json::UInt64)getValueOfShareId();
    } else {
        ret["share_id"] = Json::Value();
    }
    if (getItemType()) {
        ret["item_type"] = getValueOfItemType();
    } else {
        ret["item_type"] = Json::Value();
    }
    if (getItemId()) {
        ret["item_id"] = (Json::UInt64)getValueOfItemId();
    } else {
        ret["item_id"] = Json::Value();
    }
    if (getCreatedAt()) {
        ret["created_at"] = getCreatedAt()->toDbStringLocal();
    } else {
        ret["created_at"] = Json::Value();
    }
    return ret;
}

bool ShareFiles::validateJsonForCreation(const Json::Value& pJson, std::string& err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, true)) {
            return false;
        }
    }
    if (pJson.isMember("share_id")) {
        if (!validJsonOfField(1, "share_id", pJson["share_id"], err, true)) {
            return false;
        }
    } else {
        err = "The share_id column cannot be null";
        return false;
    }
    if (pJson.isMember("item_type")) {
        if (!validJsonOfField(2, "item_type", pJson["item_type"], err, true)) {
            return false;
        }
    } else {
        err = "The item_type column cannot be null";
        return false;
    }
    if (pJson.isMember("item_id")) {
        if (!validJsonOfField(3, "item_id", pJson["item_id"], err, true)) {
            return false;
        }
    } else {
        err = "The item_id column cannot be null";
        return false;
    }
    if (pJson.isMember("created_at")) {
        if (!validJsonOfField(4, "created_at", pJson["created_at"], err, true)) {
            return false;
        }
    }
    return true;
}

bool ShareFiles::validateMasqueradedJsonForCreation(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector, std::string& err) {
    if (pMasqueradingVector.size() != 5) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty()) {
            if (pJson.isMember(pMasqueradingVector[0])) {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true)) {
                    return false;
                }
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (pJson.isMember(pMasqueradingVector[1])) {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true)) {
                    return false;
                }
            } else {
                err = "The " + pMasqueradingVector[1] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (pJson.isMember(pMasqueradingVector[2])) {
                if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true)) {
                    return false;
                }
            } else {
                err = "The " + pMasqueradingVector[2] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (pJson.isMember(pMasqueradingVector[3])) {
                if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true)) {
                    return false;
                }
            } else {
                err = "The " + pMasqueradingVector[3] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[4].empty()) {
            if (pJson.isMember(pMasqueradingVector[4])) {
                if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true)) {
                    return false;
                }
            }
        }
    } catch (const Json::LogicError& e) {
        err = e.what();
        return false;
    }
    return true;
}

bool ShareFiles::validateJsonForUpdate(const Json::Value& pJson, std::string& err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, false)) {
            return false;
        }
    } else {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("share_id")) {
        if (!validJsonOfField(1, "share_id", pJson["share_id"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("item_type")) {
        if (!validJsonOfField(2, "item_type", pJson["item_type"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("item_id")) {
        if (!validJsonOfField(3, "item_id", pJson["item_id"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("created_at")) {
        if (!validJsonOfField(4, "created_at", pJson["created_at"], err, false)) {
            return false;
        }
    }
    return true;
}

bool ShareFiles::validateMasqueradedJsonForUpdate(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector, std::string& err) {
    if (pMasqueradingVector.size() != 5) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false)) {
                return false;
            }
        } else {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
            if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
            if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
            if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false)) {
                return false;
            }
        }
    } catch (const Json::LogicError& e) {
        err = e.what();
        return false;
    }
    return true;
}

bool ShareFiles::validJsonOfField(size_t index, const std::string& fieldName, const Json::Value& pJson, std::string& err, bool isForCreation) {
    switch (index) {
        case 0:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (isForCreation) {
                err = "The automatic primary key cannot be set";
                return false;
            }
            if (!pJson.isUInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isUInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 2:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 3:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isUInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 4:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
    }
    return true;
}
