/**
 *
 *  Trash.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Trash.hpp"

#include <string>

#include <drogon/utils/Utilities.h>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::disk;

const std::string Trash::Cols::_id = "id";
const std::string Trash::Cols::_user_id = "user_id";
const std::string Trash::Cols::_item_type = "item_type";
const std::string Trash::Cols::_item_id = "item_id";
const std::string Trash::Cols::_item_name = "item_name";
const std::string Trash::Cols::_item_size = "item_size";
const std::string Trash::Cols::_original_folder_id = "original_folder_id";
const std::string Trash::Cols::_original_path = "original_path";
const std::string Trash::Cols::_item_data = "item_data";
const std::string Trash::Cols::_deleted_at = "deleted_at";
const std::string Trash::Cols::_expires_at = "expires_at";
const std::string Trash::primaryKeyName = "id";
const bool Trash::hasPrimaryKey = true;
const std::string Trash::tableName = "trash";

const std::vector<typename Trash::MetaData> Trash::metaData_ = {
    {                 "id",        "uint64_t",       "bigint unsigned",    8, 1, 1, 1 },
    {            "user_id",        "uint64_t",       "bigint unsigned",    8, 0, 0, 1 },
    {          "item_type",     "std::string", "enum('file','folder')",    0, 0, 0, 1 },
    {            "item_id",        "uint64_t",       "bigint unsigned",    8, 0, 0, 1 },
    {          "item_name",     "std::string",          "varchar(255)",  255, 0, 0, 1 },
    {          "item_size",        "uint64_t",       "bigint unsigned",    8, 0, 0, 1 },
    { "original_folder_id",        "uint64_t",       "bigint unsigned",    8, 0, 0, 1 },
    {      "original_path",     "std::string",         "varchar(4096)", 4096, 0, 0, 1 },
    {          "item_data",     "std::string",                  "json",    0, 0, 0, 0 },
    {         "deleted_at", "::trantor::Date",              "datetime",    0, 0, 0, 1 },
    {         "expires_at", "::trantor::Date",              "datetime",    0, 0, 0, 1 }
};

const std::string& Trash::getColumnName(size_t index) noexcept(false) {
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}

Trash::Trash(const Row& r, const ssize_t indexOffset) noexcept {
    if (indexOffset < 0) {
        if (!r["id"].isNull()) {
            id_ = std::make_shared<uint64_t>(r["id"].as<uint64_t>());
        }
        if (!r["user_id"].isNull()) {
            userId_ = std::make_shared<uint64_t>(r["user_id"].as<uint64_t>());
        }
        if (!r["item_type"].isNull()) {
            itemType_ = std::make_shared<std::string>(r["item_type"].as<std::string>());
        }
        if (!r["item_id"].isNull()) {
            itemId_ = std::make_shared<uint64_t>(r["item_id"].as<uint64_t>());
        }
        if (!r["item_name"].isNull()) {
            itemName_ = std::make_shared<std::string>(r["item_name"].as<std::string>());
        }
        if (!r["item_size"].isNull()) {
            itemSize_ = std::make_shared<uint64_t>(r["item_size"].as<uint64_t>());
        }
        if (!r["original_folder_id"].isNull()) {
            originalFolderId_ = std::make_shared<uint64_t>(r["original_folder_id"].as<uint64_t>());
        }
        if (!r["original_path"].isNull()) {
            originalPath_ = std::make_shared<std::string>(r["original_path"].as<std::string>());
        }
        if (!r["item_data"].isNull()) {
            itemData_ = std::make_shared<std::string>(r["item_data"].as<std::string>());
        }
        if (!r["deleted_at"].isNull()) {
            auto timeStr = r["deleted_at"].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
        if (!r["expires_at"].isNull()) {
            auto timeStr = r["expires_at"].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    } else {
        size_t offset = (size_t)indexOffset;
        if (offset + 11 > r.size()) {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull()) {
            id_ = std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 1;
        if (!r[index].isNull()) {
            userId_ = std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 2;
        if (!r[index].isNull()) {
            itemType_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if (!r[index].isNull()) {
            itemId_ = std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 4;
        if (!r[index].isNull()) {
            itemName_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if (!r[index].isNull()) {
            itemSize_ = std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 6;
        if (!r[index].isNull()) {
            originalFolderId_ = std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 7;
        if (!r[index].isNull()) {
            originalPath_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if (!r[index].isNull()) {
            itemData_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if (!r[index].isNull()) {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
        index = offset + 10;
        if (!r[index].isNull()) {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

Trash::Trash(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 11) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            userId_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            itemType_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            itemId_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull()) {
            itemName_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull()) {
            itemSize_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[5]].asUInt64());
        }
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
        dirtyFlag_[6] = true;
        if (!pJson[pMasqueradingVector[6]].isNull()) {
            originalFolderId_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[6]].asUInt64());
        }
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
        dirtyFlag_[7] = true;
        if (!pJson[pMasqueradingVector[7]].isNull()) {
            originalPath_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
        dirtyFlag_[8] = true;
        if (!pJson[pMasqueradingVector[8]].isNull()) {
            itemData_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
        dirtyFlag_[9] = true;
        if (!pJson[pMasqueradingVector[9]].isNull()) {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
    if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
        dirtyFlag_[10] = true;
        if (!pJson[pMasqueradingVector[10]].isNull()) {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

Trash::Trash(const Json::Value& pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        dirtyFlag_[0] = true;
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
        }
    }
    if (pJson.isMember("user_id")) {
        dirtyFlag_[1] = true;
        if (!pJson["user_id"].isNull()) {
            userId_ = std::make_shared<uint64_t>((uint64_t)pJson["user_id"].asUInt64());
        }
    }
    if (pJson.isMember("item_type")) {
        dirtyFlag_[2] = true;
        if (!pJson["item_type"].isNull()) {
            itemType_ = std::make_shared<std::string>(pJson["item_type"].asString());
        }
    }
    if (pJson.isMember("item_id")) {
        dirtyFlag_[3] = true;
        if (!pJson["item_id"].isNull()) {
            itemId_ = std::make_shared<uint64_t>((uint64_t)pJson["item_id"].asUInt64());
        }
    }
    if (pJson.isMember("item_name")) {
        dirtyFlag_[4] = true;
        if (!pJson["item_name"].isNull()) {
            itemName_ = std::make_shared<std::string>(pJson["item_name"].asString());
        }
    }
    if (pJson.isMember("item_size")) {
        dirtyFlag_[5] = true;
        if (!pJson["item_size"].isNull()) {
            itemSize_ = std::make_shared<uint64_t>((uint64_t)pJson["item_size"].asUInt64());
        }
    }
    if (pJson.isMember("original_folder_id")) {
        dirtyFlag_[6] = true;
        if (!pJson["original_folder_id"].isNull()) {
            originalFolderId_ = std::make_shared<uint64_t>((uint64_t)pJson["original_folder_id"].asUInt64());
        }
    }
    if (pJson.isMember("original_path")) {
        dirtyFlag_[7] = true;
        if (!pJson["original_path"].isNull()) {
            originalPath_ = std::make_shared<std::string>(pJson["original_path"].asString());
        }
    }
    if (pJson.isMember("item_data")) {
        dirtyFlag_[8] = true;
        if (!pJson["item_data"].isNull()) {
            itemData_ = std::make_shared<std::string>(pJson["item_data"].asString());
        }
    }
    if (pJson.isMember("deleted_at")) {
        dirtyFlag_[9] = true;
        if (!pJson["deleted_at"].isNull()) {
            auto timeStr = pJson["deleted_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
    if (pJson.isMember("expires_at")) {
        dirtyFlag_[10] = true;
        if (!pJson["expires_at"].isNull()) {
            auto timeStr = pJson["expires_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

void Trash::updateByMasqueradedJson(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 11) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            userId_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            itemType_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            itemId_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull()) {
            itemName_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull()) {
            itemSize_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[5]].asUInt64());
        }
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
        dirtyFlag_[6] = true;
        if (!pJson[pMasqueradingVector[6]].isNull()) {
            originalFolderId_ = std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[6]].asUInt64());
        }
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
        dirtyFlag_[7] = true;
        if (!pJson[pMasqueradingVector[7]].isNull()) {
            originalPath_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
        dirtyFlag_[8] = true;
        if (!pJson[pMasqueradingVector[8]].isNull()) {
            itemData_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
        dirtyFlag_[9] = true;
        if (!pJson[pMasqueradingVector[9]].isNull()) {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
    if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
        dirtyFlag_[10] = true;
        if (!pJson[pMasqueradingVector[10]].isNull()) {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

void Trash::updateByJson(const Json::Value& pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
        }
    }
    if (pJson.isMember("user_id")) {
        dirtyFlag_[1] = true;
        if (!pJson["user_id"].isNull()) {
            userId_ = std::make_shared<uint64_t>((uint64_t)pJson["user_id"].asUInt64());
        }
    }
    if (pJson.isMember("item_type")) {
        dirtyFlag_[2] = true;
        if (!pJson["item_type"].isNull()) {
            itemType_ = std::make_shared<std::string>(pJson["item_type"].asString());
        }
    }
    if (pJson.isMember("item_id")) {
        dirtyFlag_[3] = true;
        if (!pJson["item_id"].isNull()) {
            itemId_ = std::make_shared<uint64_t>((uint64_t)pJson["item_id"].asUInt64());
        }
    }
    if (pJson.isMember("item_name")) {
        dirtyFlag_[4] = true;
        if (!pJson["item_name"].isNull()) {
            itemName_ = std::make_shared<std::string>(pJson["item_name"].asString());
        }
    }
    if (pJson.isMember("item_size")) {
        dirtyFlag_[5] = true;
        if (!pJson["item_size"].isNull()) {
            itemSize_ = std::make_shared<uint64_t>((uint64_t)pJson["item_size"].asUInt64());
        }
    }
    if (pJson.isMember("original_folder_id")) {
        dirtyFlag_[6] = true;
        if (!pJson["original_folder_id"].isNull()) {
            originalFolderId_ = std::make_shared<uint64_t>((uint64_t)pJson["original_folder_id"].asUInt64());
        }
    }
    if (pJson.isMember("original_path")) {
        dirtyFlag_[7] = true;
        if (!pJson["original_path"].isNull()) {
            originalPath_ = std::make_shared<std::string>(pJson["original_path"].asString());
        }
    }
    if (pJson.isMember("item_data")) {
        dirtyFlag_[8] = true;
        if (!pJson["item_data"].isNull()) {
            itemData_ = std::make_shared<std::string>(pJson["item_data"].asString());
        }
    }
    if (pJson.isMember("deleted_at")) {
        dirtyFlag_[9] = true;
        if (!pJson["deleted_at"].isNull()) {
            auto timeStr = pJson["deleted_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
    if (pJson.isMember("expires_at")) {
        dirtyFlag_[10] = true;
        if (!pJson["expires_at"].isNull()) {
            auto timeStr = pJson["expires_at"].asString();
            struct tm stm;
            memset(&stm, 0, sizeof(stm));
            auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if (p) {
                if (*p == '.') {
                    std::string decimals(p + 1, &timeStr[timeStr.length()]);
                    while (decimals.length() < 6) {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expiresAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
            }
        }
    }
}

const uint64_t& Trash::getValueOfId() const noexcept {
    static const uint64_t defaultValue = uint64_t();
    if (id_) {
        return *id_;
    }
    return defaultValue;
}

const std::shared_ptr<uint64_t>& Trash::getId() const noexcept {
    return id_;
}

void Trash::setId(const uint64_t& pId) noexcept {
    id_ = std::make_shared<uint64_t>(pId);
    dirtyFlag_[0] = true;
}

const typename Trash::PrimaryKeyType& Trash::getPrimaryKey() const {
    assert(id_);
    return *id_;
}

const uint64_t& Trash::getValueOfUserId() const noexcept {
    static const uint64_t defaultValue = uint64_t();
    if (userId_) {
        return *userId_;
    }
    return defaultValue;
}

const std::shared_ptr<uint64_t>& Trash::getUserId() const noexcept {
    return userId_;
}

void Trash::setUserId(const uint64_t& pUserId) noexcept {
    userId_ = std::make_shared<uint64_t>(pUserId);
    dirtyFlag_[1] = true;
}

const std::string& Trash::getValueOfItemType() const noexcept {
    static const std::string defaultValue = std::string();
    if (itemType_) {
        return *itemType_;
    }
    return defaultValue;
}

const std::shared_ptr<std::string>& Trash::getItemType() const noexcept {
    return itemType_;
}

void Trash::setItemType(const std::string& pItemType) noexcept {
    itemType_ = std::make_shared<std::string>(pItemType);
    dirtyFlag_[2] = true;
}

void Trash::setItemType(std::string&& pItemType) noexcept {
    itemType_ = std::make_shared<std::string>(std::move(pItemType));
    dirtyFlag_[2] = true;
}

const uint64_t& Trash::getValueOfItemId() const noexcept {
    static const uint64_t defaultValue = uint64_t();
    if (itemId_) {
        return *itemId_;
    }
    return defaultValue;
}

const std::shared_ptr<uint64_t>& Trash::getItemId() const noexcept {
    return itemId_;
}

void Trash::setItemId(const uint64_t& pItemId) noexcept {
    itemId_ = std::make_shared<uint64_t>(pItemId);
    dirtyFlag_[3] = true;
}

const std::string& Trash::getValueOfItemName() const noexcept {
    static const std::string defaultValue = std::string();
    if (itemName_) {
        return *itemName_;
    }
    return defaultValue;
}

const std::shared_ptr<std::string>& Trash::getItemName() const noexcept {
    return itemName_;
}

void Trash::setItemName(const std::string& pItemName) noexcept {
    itemName_ = std::make_shared<std::string>(pItemName);
    dirtyFlag_[4] = true;
}

void Trash::setItemName(std::string&& pItemName) noexcept {
    itemName_ = std::make_shared<std::string>(std::move(pItemName));
    dirtyFlag_[4] = true;
}

const uint64_t& Trash::getValueOfItemSize() const noexcept {
    static const uint64_t defaultValue = uint64_t();
    if (itemSize_) {
        return *itemSize_;
    }
    return defaultValue;
}

const std::shared_ptr<uint64_t>& Trash::getItemSize() const noexcept {
    return itemSize_;
}

void Trash::setItemSize(const uint64_t& pItemSize) noexcept {
    itemSize_ = std::make_shared<uint64_t>(pItemSize);
    dirtyFlag_[5] = true;
}

const uint64_t& Trash::getValueOfOriginalFolderId() const noexcept {
    static const uint64_t defaultValue = uint64_t();
    if (originalFolderId_) {
        return *originalFolderId_;
    }
    return defaultValue;
}

const std::shared_ptr<uint64_t>& Trash::getOriginalFolderId() const noexcept {
    return originalFolderId_;
}

void Trash::setOriginalFolderId(const uint64_t& pOriginalFolderId) noexcept {
    originalFolderId_ = std::make_shared<uint64_t>(pOriginalFolderId);
    dirtyFlag_[6] = true;
}

const std::string& Trash::getValueOfOriginalPath() const noexcept {
    static const std::string defaultValue = std::string();
    if (originalPath_) {
        return *originalPath_;
    }
    return defaultValue;
}

const std::shared_ptr<std::string>& Trash::getOriginalPath() const noexcept {
    return originalPath_;
}

void Trash::setOriginalPath(const std::string& pOriginalPath) noexcept {
    originalPath_ = std::make_shared<std::string>(pOriginalPath);
    dirtyFlag_[7] = true;
}

void Trash::setOriginalPath(std::string&& pOriginalPath) noexcept {
    originalPath_ = std::make_shared<std::string>(std::move(pOriginalPath));
    dirtyFlag_[7] = true;
}

const std::string& Trash::getValueOfItemData() const noexcept {
    static const std::string defaultValue = std::string();
    if (itemData_) {
        return *itemData_;
    }
    return defaultValue;
}

const std::shared_ptr<std::string>& Trash::getItemData() const noexcept {
    return itemData_;
}

void Trash::setItemData(const std::string& pItemData) noexcept {
    itemData_ = std::make_shared<std::string>(pItemData);
    dirtyFlag_[8] = true;
}

void Trash::setItemData(std::string&& pItemData) noexcept {
    itemData_ = std::make_shared<std::string>(std::move(pItemData));
    dirtyFlag_[8] = true;
}

void Trash::setItemDataToNull() noexcept {
    itemData_.reset();
    dirtyFlag_[8] = true;
}

const ::trantor::Date& Trash::getValueOfDeletedAt() const noexcept {
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if (deletedAt_) {
        return *deletedAt_;
    }
    return defaultValue;
}

const std::shared_ptr<::trantor::Date>& Trash::getDeletedAt() const noexcept {
    return deletedAt_;
}

void Trash::setDeletedAt(const ::trantor::Date& pDeletedAt) noexcept {
    deletedAt_ = std::make_shared<::trantor::Date>(pDeletedAt);
    dirtyFlag_[9] = true;
}

const ::trantor::Date& Trash::getValueOfExpiresAt() const noexcept {
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if (expiresAt_) {
        return *expiresAt_;
    }
    return defaultValue;
}

const std::shared_ptr<::trantor::Date>& Trash::getExpiresAt() const noexcept {
    return expiresAt_;
}

void Trash::setExpiresAt(const ::trantor::Date& pExpiresAt) noexcept {
    expiresAt_ = std::make_shared<::trantor::Date>(pExpiresAt);
    dirtyFlag_[10] = true;
}

void Trash::updateId(const uint64_t id) {
    id_ = std::make_shared<uint64_t>(id);
}

const std::vector<std::string>& Trash::insertColumns() noexcept {
    static const std::vector<std::string> inCols = {
        "user_id",
        "item_type",
        "item_id",
        "item_name",
        "item_size",
        "original_folder_id",
        "original_path",
        "item_data",
        "deleted_at",
        "expires_at"
    };
    return inCols;
}

void Trash::outputArgs(drogon::orm::internal::SqlBinder& binder) const {
    if (dirtyFlag_[1]) {
        if (getUserId()) {
            binder << getValueOfUserId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getItemType()) {
            binder << getValueOfItemType();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getItemId()) {
            binder << getValueOfItemId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4]) {
        if (getItemName()) {
            binder << getValueOfItemName();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5]) {
        if (getItemSize()) {
            binder << getValueOfItemSize();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[6]) {
        if (getOriginalFolderId()) {
            binder << getValueOfOriginalFolderId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[7]) {
        if (getOriginalPath()) {
            binder << getValueOfOriginalPath();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[8]) {
        if (getItemData()) {
            binder << getValueOfItemData();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[9]) {
        if (getDeletedAt()) {
            binder << getValueOfDeletedAt();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[10]) {
        if (getExpiresAt()) {
            binder << getValueOfExpiresAt();
        } else {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Trash::updateColumns() const {
    std::vector<std::string> ret;
    if (dirtyFlag_[1]) {
        ret.push_back(getColumnName(1));
    }
    if (dirtyFlag_[2]) {
        ret.push_back(getColumnName(2));
    }
    if (dirtyFlag_[3]) {
        ret.push_back(getColumnName(3));
    }
    if (dirtyFlag_[4]) {
        ret.push_back(getColumnName(4));
    }
    if (dirtyFlag_[5]) {
        ret.push_back(getColumnName(5));
    }
    if (dirtyFlag_[6]) {
        ret.push_back(getColumnName(6));
    }
    if (dirtyFlag_[7]) {
        ret.push_back(getColumnName(7));
    }
    if (dirtyFlag_[8]) {
        ret.push_back(getColumnName(8));
    }
    if (dirtyFlag_[9]) {
        ret.push_back(getColumnName(9));
    }
    if (dirtyFlag_[10]) {
        ret.push_back(getColumnName(10));
    }
    return ret;
}

void Trash::updateArgs(drogon::orm::internal::SqlBinder& binder) const {
    if (dirtyFlag_[1]) {
        if (getUserId()) {
            binder << getValueOfUserId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getItemType()) {
            binder << getValueOfItemType();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getItemId()) {
            binder << getValueOfItemId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4]) {
        if (getItemName()) {
            binder << getValueOfItemName();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5]) {
        if (getItemSize()) {
            binder << getValueOfItemSize();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[6]) {
        if (getOriginalFolderId()) {
            binder << getValueOfOriginalFolderId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[7]) {
        if (getOriginalPath()) {
            binder << getValueOfOriginalPath();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[8]) {
        if (getItemData()) {
            binder << getValueOfItemData();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[9]) {
        if (getDeletedAt()) {
            binder << getValueOfDeletedAt();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[10]) {
        if (getExpiresAt()) {
            binder << getValueOfExpiresAt();
        } else {
            binder << nullptr;
        }
    }
}

Json::Value Trash::toJson() const {
    Json::Value ret;
    if (getId()) {
        ret["id"] = (Json::UInt64)getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getUserId()) {
        ret["user_id"] = (Json::UInt64)getValueOfUserId();
    } else {
        ret["user_id"] = Json::Value();
    }
    if (getItemType()) {
        ret["item_type"] = getValueOfItemType();
    } else {
        ret["item_type"] = Json::Value();
    }
    if (getItemId()) {
        ret["item_id"] = (Json::UInt64)getValueOfItemId();
    } else {
        ret["item_id"] = Json::Value();
    }
    if (getItemName()) {
        ret["item_name"] = getValueOfItemName();
    } else {
        ret["item_name"] = Json::Value();
    }
    if (getItemSize()) {
        ret["item_size"] = (Json::UInt64)getValueOfItemSize();
    } else {
        ret["item_size"] = Json::Value();
    }
    if (getOriginalFolderId()) {
        ret["original_folder_id"] = (Json::UInt64)getValueOfOriginalFolderId();
    } else {
        ret["original_folder_id"] = Json::Value();
    }
    if (getOriginalPath()) {
        ret["original_path"] = getValueOfOriginalPath();
    } else {
        ret["original_path"] = Json::Value();
    }
    if (getItemData()) {
        ret["item_data"] = getValueOfItemData();
    } else {
        ret["item_data"] = Json::Value();
    }
    if (getDeletedAt()) {
        ret["deleted_at"] = getDeletedAt()->toDbStringLocal();
    } else {
        ret["deleted_at"] = Json::Value();
    }
    if (getExpiresAt()) {
        ret["expires_at"] = getExpiresAt()->toDbStringLocal();
    } else {
        ret["expires_at"] = Json::Value();
    }
    return ret;
}

Json::Value Trash::toMasqueradedJson(
    const std::vector<std::string>& pMasqueradingVector
) const {
    Json::Value ret;
    if (pMasqueradingVector.size() == 11) {
        if (!pMasqueradingVector[0].empty()) {
            if (getId()) {
                ret[pMasqueradingVector[0]] = (Json::UInt64)getValueOfId();
            } else {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (getUserId()) {
                ret[pMasqueradingVector[1]] = (Json::UInt64)getValueOfUserId();
            } else {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (getItemType()) {
                ret[pMasqueradingVector[2]] = getValueOfItemType();
            } else {
                ret[pMasqueradingVector[2]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (getItemId()) {
                ret[pMasqueradingVector[3]] = (Json::UInt64)getValueOfItemId();
            } else {
                ret[pMasqueradingVector[3]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[4].empty()) {
            if (getItemName()) {
                ret[pMasqueradingVector[4]] = getValueOfItemName();
            } else {
                ret[pMasqueradingVector[4]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[5].empty()) {
            if (getItemSize()) {
                ret[pMasqueradingVector[5]] = (Json::UInt64)getValueOfItemSize();
            } else {
                ret[pMasqueradingVector[5]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[6].empty()) {
            if (getOriginalFolderId()) {
                ret[pMasqueradingVector[6]] = (Json::UInt64)getValueOfOriginalFolderId();
            } else {
                ret[pMasqueradingVector[6]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[7].empty()) {
            if (getOriginalPath()) {
                ret[pMasqueradingVector[7]] = getValueOfOriginalPath();
            } else {
                ret[pMasqueradingVector[7]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[8].empty()) {
            if (getItemData()) {
                ret[pMasqueradingVector[8]] = getValueOfItemData();
            } else {
                ret[pMasqueradingVector[8]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[9].empty()) {
            if (getDeletedAt()) {
                ret[pMasqueradingVector[9]] = getDeletedAt()->toDbStringLocal();
            } else {
                ret[pMasqueradingVector[9]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[10].empty()) {
            if (getExpiresAt()) {
                ret[pMasqueradingVector[10]] = getExpiresAt()->toDbStringLocal();
            } else {
                ret[pMasqueradingVector[10]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getId()) {
        ret["id"] = (Json::UInt64)getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getUserId()) {
        ret["user_id"] = (Json::UInt64)getValueOfUserId();
    } else {
        ret["user_id"] = Json::Value();
    }
    if (getItemType()) {
        ret["item_type"] = getValueOfItemType();
    } else {
        ret["item_type"] = Json::Value();
    }
    if (getItemId()) {
        ret["item_id"] = (Json::UInt64)getValueOfItemId();
    } else {
        ret["item_id"] = Json::Value();
    }
    if (getItemName()) {
        ret["item_name"] = getValueOfItemName();
    } else {
        ret["item_name"] = Json::Value();
    }
    if (getItemSize()) {
        ret["item_size"] = (Json::UInt64)getValueOfItemSize();
    } else {
        ret["item_size"] = Json::Value();
    }
    if (getOriginalFolderId()) {
        ret["original_folder_id"] = (Json::UInt64)getValueOfOriginalFolderId();
    } else {
        ret["original_folder_id"] = Json::Value();
    }
    if (getOriginalPath()) {
        ret["original_path"] = getValueOfOriginalPath();
    } else {
        ret["original_path"] = Json::Value();
    }
    if (getItemData()) {
        ret["item_data"] = getValueOfItemData();
    } else {
        ret["item_data"] = Json::Value();
    }
    if (getDeletedAt()) {
        ret["deleted_at"] = getDeletedAt()->toDbStringLocal();
    } else {
        ret["deleted_at"] = Json::Value();
    }
    if (getExpiresAt()) {
        ret["expires_at"] = getExpiresAt()->toDbStringLocal();
    } else {
        ret["expires_at"] = Json::Value();
    }
    return ret;
}

bool Trash::validateJsonForCreation(const Json::Value& pJson, std::string& err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, true)) {
            return false;
        }
    }
    if (pJson.isMember("user_id")) {
        if (!validJsonOfField(1, "user_id", pJson["user_id"], err, true)) {
            return false;
        }
    } else {
        err = "The user_id column cannot be null";
        return false;
    }
    if (pJson.isMember("item_type")) {
        if (!validJsonOfField(2, "item_type", pJson["item_type"], err, true)) {
            return false;
        }
    } else {
        err = "The item_type column cannot be null";
        return false;
    }
    if (pJson.isMember("item_id")) {
        if (!validJsonOfField(3, "item_id", pJson["item_id"], err, true)) {
            return false;
        }
    } else {
        err = "The item_id column cannot be null";
        return false;
    }
    if (pJson.isMember("item_name")) {
        if (!validJsonOfField(4, "item_name", pJson["item_name"], err, true)) {
            return false;
        }
    } else {
        err = "The item_name column cannot be null";
        return false;
    }
    if (pJson.isMember("item_size")) {
        if (!validJsonOfField(5, "item_size", pJson["item_size"], err, true)) {
            return false;
        }
    }
    if (pJson.isMember("original_folder_id")) {
        if (!validJsonOfField(6, "original_folder_id", pJson["original_folder_id"], err, true)) {
            return false;
        }
    }
    if (pJson.isMember("original_path")) {
        if (!validJsonOfField(7, "original_path", pJson["original_path"], err, true)) {
            return false;
        }
    } else {
        err = "The original_path column cannot be null";
        return false;
    }
    if (pJson.isMember("item_data")) {
        if (!validJsonOfField(8, "item_data", pJson["item_data"], err, true)) {
            return false;
        }
    }
    if (pJson.isMember("deleted_at")) {
        if (!validJsonOfField(9, "deleted_at", pJson["deleted_at"], err, true)) {
            return false;
        }
    }
    if (pJson.isMember("expires_at")) {
        if (!validJsonOfField(10, "expires_at", pJson["expires_at"], err, true)) {
            return false;
        }
    } else {
        err = "The expires_at column cannot be null";
        return false;
    }
    return true;
}

bool Trash::validateMasqueradedJsonForCreation(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector, std::string& err) {
    if (pMasqueradingVector.size() != 11) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty()) {
            if (pJson.isMember(pMasqueradingVector[0])) {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true)) {
                    return false;
                }
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (pJson.isMember(pMasqueradingVector[1])) {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true)) {
                    return false;
                }
            } else {
                err = "The " + pMasqueradingVector[1] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (pJson.isMember(pMasqueradingVector[2])) {
                if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true)) {
                    return false;
                }
            } else {
                err = "The " + pMasqueradingVector[2] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (pJson.isMember(pMasqueradingVector[3])) {
                if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true)) {
                    return false;
                }
            } else {
                err = "The " + pMasqueradingVector[3] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[4].empty()) {
            if (pJson.isMember(pMasqueradingVector[4])) {
                if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true)) {
                    return false;
                }
            } else {
                err = "The " + pMasqueradingVector[4] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[5].empty()) {
            if (pJson.isMember(pMasqueradingVector[5])) {
                if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true)) {
                    return false;
                }
            }
        }
        if (!pMasqueradingVector[6].empty()) {
            if (pJson.isMember(pMasqueradingVector[6])) {
                if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true)) {
                    return false;
                }
            }
        }
        if (!pMasqueradingVector[7].empty()) {
            if (pJson.isMember(pMasqueradingVector[7])) {
                if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true)) {
                    return false;
                }
            } else {
                err = "The " + pMasqueradingVector[7] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[8].empty()) {
            if (pJson.isMember(pMasqueradingVector[8])) {
                if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true)) {
                    return false;
                }
            }
        }
        if (!pMasqueradingVector[9].empty()) {
            if (pJson.isMember(pMasqueradingVector[9])) {
                if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true)) {
                    return false;
                }
            }
        }
        if (!pMasqueradingVector[10].empty()) {
            if (pJson.isMember(pMasqueradingVector[10])) {
                if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true)) {
                    return false;
                }
            } else {
                err = "The " + pMasqueradingVector[10] + " column cannot be null";
                return false;
            }
        }
    } catch (const Json::LogicError& e) {
        err = e.what();
        return false;
    }
    return true;
}

bool Trash::validateJsonForUpdate(const Json::Value& pJson, std::string& err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, false)) {
            return false;
        }
    } else {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("user_id")) {
        if (!validJsonOfField(1, "user_id", pJson["user_id"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("item_type")) {
        if (!validJsonOfField(2, "item_type", pJson["item_type"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("item_id")) {
        if (!validJsonOfField(3, "item_id", pJson["item_id"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("item_name")) {
        if (!validJsonOfField(4, "item_name", pJson["item_name"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("item_size")) {
        if (!validJsonOfField(5, "item_size", pJson["item_size"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("original_folder_id")) {
        if (!validJsonOfField(6, "original_folder_id", pJson["original_folder_id"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("original_path")) {
        if (!validJsonOfField(7, "original_path", pJson["original_path"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("item_data")) {
        if (!validJsonOfField(8, "item_data", pJson["item_data"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("deleted_at")) {
        if (!validJsonOfField(9, "deleted_at", pJson["deleted_at"], err, false)) {
            return false;
        }
    }
    if (pJson.isMember("expires_at")) {
        if (!validJsonOfField(10, "expires_at", pJson["expires_at"], err, false)) {
            return false;
        }
    }
    return true;
}

bool Trash::validateMasqueradedJsonForUpdate(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector, std::string& err) {
    if (pMasqueradingVector.size() != 11) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false)) {
                return false;
            }
        } else {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
            if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
            if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
            if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
            if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
            if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
            if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
            if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
            if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false)) {
                return false;
            }
        }
        if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
            if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false)) {
                return false;
            }
        }
    } catch (const Json::LogicError& e) {
        err = e.what();
        return false;
    }
    return true;
}

bool Trash::validJsonOfField(size_t index, const std::string& fieldName, const Json::Value& pJson, std::string& err, bool isForCreation) {
    switch (index) {
        case 0:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (isForCreation) {
                err = "The automatic primary key cannot be set";
                return false;
            }
            if (!pJson.isUInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isUInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 2:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 3:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isUInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 4:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && std::strlen(pJson.asCString()) > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }

            break;
        case 5:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isUInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 6:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isUInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 7:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && std::strlen(pJson.asCString()) > 4096) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 4096)";
                return false;
            }

            break;
        case 8:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 9:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 10:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
    }
    return true;
}
