/**
 *
 *  UploadTaskChunks.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "UploadTaskChunks.hpp"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::disk;

const std::string UploadTaskChunks::Cols::_task_id = "\"task_id\"";
const std::string UploadTaskChunks::Cols::_chunk_index = "\"chunk_index\"";
const std::string UploadTaskChunks::Cols::_uploaded_at = "\"uploaded_at\"";
const std::vector<std::string> UploadTaskChunks::primaryKeyName = {
    "task_id", "chunk_index"};
const bool UploadTaskChunks::hasPrimaryKey = true;
const std::string UploadTaskChunks::tableName = "\"upload_task_chunks\"";

const std::vector<typename UploadTaskChunks::MetaData>
    UploadTaskChunks::metaData_ = {
        {"task_id", "std::string", "character varying", 64, 0, 1, 1},
        {"chunk_index", "int32_t", "integer", 4, 0, 1, 1},
        {"uploaded_at", "::trantor::Date", "timestamp without time zone", 0, 0,
         0, 1}};
const std::string &
UploadTaskChunks::getColumnName(size_t index) noexcept(false) {
  assert(index < metaData_.size());
  return metaData_[index].colName_;
}
UploadTaskChunks::UploadTaskChunks(const Row &r,
                                   const ssize_t indexOffset) noexcept {
  if (indexOffset < 0) {
    if (!r["task_id"].isNull()) {
      taskId_ = std::make_shared<std::string>(r["task_id"].as<std::string>());
    }
    if (!r["chunk_index"].isNull()) {
      chunkIndex_ = std::make_shared<int32_t>(r["chunk_index"].as<int32_t>());
    }
    if (!r["uploaded_at"].isNull()) {
      auto timeStr = r["uploaded_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        uploadedAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  } else {
    size_t offset = (size_t)indexOffset;
    if (offset + 3 > r.size()) {
      LOG_FATAL << "Invalid SQL result for this model";
      return;
    }
    size_t index;
    index = offset + 0;
    if (!r[index].isNull()) {
      taskId_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 1;
    if (!r[index].isNull()) {
      chunkIndex_ = std::make_shared<int32_t>(r[index].as<int32_t>());
    }
    index = offset + 2;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        uploadedAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

UploadTaskChunks::UploadTaskChunks(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 3) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() &&
      pJson.isMember(pMasqueradingVector[0])) {
    dirtyFlag_[0] = true;
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      taskId_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[0]].asString());
    }
  }
  if (!pMasqueradingVector[1].empty() &&
      pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      chunkIndex_ = std::make_shared<int32_t>(
          (int32_t)pJson[pMasqueradingVector[1]].asInt64());
    }
  }
  if (!pMasqueradingVector[2].empty() &&
      pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[2]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        uploadedAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

UploadTaskChunks::UploadTaskChunks(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("task_id")) {
    dirtyFlag_[0] = true;
    if (!pJson["task_id"].isNull()) {
      taskId_ = std::make_shared<std::string>(pJson["task_id"].asString());
    }
  }
  if (pJson.isMember("chunk_index")) {
    dirtyFlag_[1] = true;
    if (!pJson["chunk_index"].isNull()) {
      chunkIndex_ =
          std::make_shared<int32_t>((int32_t)pJson["chunk_index"].asInt64());
    }
  }
  if (pJson.isMember("uploaded_at")) {
    dirtyFlag_[2] = true;
    if (!pJson["uploaded_at"].isNull()) {
      auto timeStr = pJson["uploaded_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        uploadedAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void UploadTaskChunks::updateByMasqueradedJson(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 3) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() &&
      pJson.isMember(pMasqueradingVector[0])) {
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      taskId_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[0]].asString());
    }
  }
  if (!pMasqueradingVector[1].empty() &&
      pJson.isMember(pMasqueradingVector[1])) {
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      chunkIndex_ = std::make_shared<int32_t>(
          (int32_t)pJson[pMasqueradingVector[1]].asInt64());
    }
  }
  if (!pMasqueradingVector[2].empty() &&
      pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[2]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        uploadedAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void UploadTaskChunks::updateByJson(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("task_id")) {
    if (!pJson["task_id"].isNull()) {
      taskId_ = std::make_shared<std::string>(pJson["task_id"].asString());
    }
  }
  if (pJson.isMember("chunk_index")) {
    if (!pJson["chunk_index"].isNull()) {
      chunkIndex_ =
          std::make_shared<int32_t>((int32_t)pJson["chunk_index"].asInt64());
    }
  }
  if (pJson.isMember("uploaded_at")) {
    dirtyFlag_[2] = true;
    if (!pJson["uploaded_at"].isNull()) {
      auto timeStr = pJson["uploaded_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        uploadedAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

const std::string &UploadTaskChunks::getValueOfTaskId() const noexcept {
  static const std::string defaultValue = std::string();
  if (taskId_)
    return *taskId_;
  return defaultValue;
}
const std::shared_ptr<std::string> &
UploadTaskChunks::getTaskId() const noexcept {
  return taskId_;
}
void UploadTaskChunks::setTaskId(const std::string &pTaskId) noexcept {
  taskId_ = std::make_shared<std::string>(pTaskId);
  dirtyFlag_[0] = true;
}
void UploadTaskChunks::setTaskId(std::string &&pTaskId) noexcept {
  taskId_ = std::make_shared<std::string>(std::move(pTaskId));
  dirtyFlag_[0] = true;
}

const int32_t &UploadTaskChunks::getValueOfChunkIndex() const noexcept {
  static const int32_t defaultValue = int32_t();
  if (chunkIndex_)
    return *chunkIndex_;
  return defaultValue;
}
const std::shared_ptr<int32_t> &
UploadTaskChunks::getChunkIndex() const noexcept {
  return chunkIndex_;
}
void UploadTaskChunks::setChunkIndex(const int32_t &pChunkIndex) noexcept {
  chunkIndex_ = std::make_shared<int32_t>(pChunkIndex);
  dirtyFlag_[1] = true;
}

const ::trantor::Date &UploadTaskChunks::getValueOfUploadedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (uploadedAt_)
    return *uploadedAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &
UploadTaskChunks::getUploadedAt() const noexcept {
  return uploadedAt_;
}
void UploadTaskChunks::setUploadedAt(
    const ::trantor::Date &pUploadedAt) noexcept {
  uploadedAt_ = std::make_shared<::trantor::Date>(pUploadedAt);
  dirtyFlag_[2] = true;
}

void UploadTaskChunks::updateId(const uint64_t id) {}
typename UploadTaskChunks::PrimaryKeyType
UploadTaskChunks::getPrimaryKey() const {
  return std::make_tuple(*taskId_, *chunkIndex_);
}

const std::vector<std::string> &UploadTaskChunks::insertColumns() noexcept {
  static const std::vector<std::string> inCols = {"task_id", "chunk_index",
                                                  "uploaded_at"};
  return inCols;
}

void UploadTaskChunks::outputArgs(
    drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[0]) {
    if (getTaskId()) {
      binder << getValueOfTaskId();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[1]) {
    if (getChunkIndex()) {
      binder << getValueOfChunkIndex();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getUploadedAt()) {
      binder << getValueOfUploadedAt();
    } else {
      binder << nullptr;
    }
  }
}

const std::vector<std::string> UploadTaskChunks::updateColumns() const {
  std::vector<std::string> ret;
  if (dirtyFlag_[0]) {
    ret.push_back(getColumnName(0));
  }
  if (dirtyFlag_[1]) {
    ret.push_back(getColumnName(1));
  }
  if (dirtyFlag_[2]) {
    ret.push_back(getColumnName(2));
  }
  return ret;
}

void UploadTaskChunks::updateArgs(
    drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[0]) {
    if (getTaskId()) {
      binder << getValueOfTaskId();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[1]) {
    if (getChunkIndex()) {
      binder << getValueOfChunkIndex();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getUploadedAt()) {
      binder << getValueOfUploadedAt();
    } else {
      binder << nullptr;
    }
  }
}
Json::Value UploadTaskChunks::toJson() const {
  Json::Value ret;
  if (getTaskId()) {
    ret["task_id"] = getValueOfTaskId();
  } else {
    ret["task_id"] = Json::Value();
  }
  if (getChunkIndex()) {
    ret["chunk_index"] = getValueOfChunkIndex();
  } else {
    ret["chunk_index"] = Json::Value();
  }
  if (getUploadedAt()) {
    ret["uploaded_at"] = getUploadedAt()->toDbStringLocal();
  } else {
    ret["uploaded_at"] = Json::Value();
  }
  return ret;
}

Json::Value UploadTaskChunks::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const {
  Json::Value ret;
  if (pMasqueradingVector.size() == 3) {
    if (!pMasqueradingVector[0].empty()) {
      if (getTaskId()) {
        ret[pMasqueradingVector[0]] = getValueOfTaskId();
      } else {
        ret[pMasqueradingVector[0]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (getChunkIndex()) {
        ret[pMasqueradingVector[1]] = getValueOfChunkIndex();
      } else {
        ret[pMasqueradingVector[1]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (getUploadedAt()) {
        ret[pMasqueradingVector[2]] = getUploadedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[2]] = Json::Value();
      }
    }
    return ret;
  }
  LOG_ERROR << "Masquerade failed";
  if (getTaskId()) {
    ret["task_id"] = getValueOfTaskId();
  } else {
    ret["task_id"] = Json::Value();
  }
  if (getChunkIndex()) {
    ret["chunk_index"] = getValueOfChunkIndex();
  } else {
    ret["chunk_index"] = Json::Value();
  }
  if (getUploadedAt()) {
    ret["uploaded_at"] = getUploadedAt()->toDbStringLocal();
  } else {
    ret["uploaded_at"] = Json::Value();
  }
  return ret;
}

bool UploadTaskChunks::validateJsonForCreation(const Json::Value &pJson,
                                               std::string &err) {
  if (pJson.isMember("task_id")) {
    if (!validJsonOfField(0, "task_id", pJson["task_id"], err, true))
      return false;
  } else {
    err = "The task_id column cannot be null";
    return false;
  }
  if (pJson.isMember("chunk_index")) {
    if (!validJsonOfField(1, "chunk_index", pJson["chunk_index"], err, true))
      return false;
  } else {
    err = "The chunk_index column cannot be null";
    return false;
  }
  if (pJson.isMember("uploaded_at")) {
    if (!validJsonOfField(2, "uploaded_at", pJson["uploaded_at"], err, true))
      return false;
  }
  return true;
}
bool UploadTaskChunks::validateMasqueradedJsonForCreation(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector, std::string &err) {
  if (pMasqueradingVector.size() != 3) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty()) {
      if (pJson.isMember(pMasqueradingVector[0])) {
        if (!validJsonOfField(0, pMasqueradingVector[0],
                              pJson[pMasqueradingVector[0]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[0] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (pJson.isMember(pMasqueradingVector[1])) {
        if (!validJsonOfField(1, pMasqueradingVector[1],
                              pJson[pMasqueradingVector[1]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[1] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (pJson.isMember(pMasqueradingVector[2])) {
        if (!validJsonOfField(2, pMasqueradingVector[2],
                              pJson[pMasqueradingVector[2]], err, true))
          return false;
      }
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool UploadTaskChunks::validateJsonForUpdate(const Json::Value &pJson,
                                             std::string &err) {
  if (pJson.isMember("task_id")) {
    if (!validJsonOfField(0, "task_id", pJson["task_id"], err, false))
      return false;
  } else {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if (pJson.isMember("chunk_index")) {
    if (!validJsonOfField(1, "chunk_index", pJson["chunk_index"], err, false))
      return false;
  } else {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if (pJson.isMember("uploaded_at")) {
    if (!validJsonOfField(2, "uploaded_at", pJson["uploaded_at"], err, false))
      return false;
  }
  return true;
}
bool UploadTaskChunks::validateMasqueradedJsonForUpdate(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector, std::string &err) {
  if (pMasqueradingVector.size() != 3) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty() &&
        pJson.isMember(pMasqueradingVector[0])) {
      if (!validJsonOfField(0, pMasqueradingVector[0],
                            pJson[pMasqueradingVector[0]], err, false))
        return false;
    } else {
      err =
          "The value of primary key must be set in the json object for update";
      return false;
    }
    if (!pMasqueradingVector[1].empty() &&
        pJson.isMember(pMasqueradingVector[1])) {
      if (!validJsonOfField(1, pMasqueradingVector[1],
                            pJson[pMasqueradingVector[1]], err, false))
        return false;
    } else {
      err =
          "The value of primary key must be set in the json object for update";
      return false;
    }
    if (!pMasqueradingVector[2].empty() &&
        pJson.isMember(pMasqueradingVector[2])) {
      if (!validJsonOfField(2, pMasqueradingVector[2],
                            pJson[pMasqueradingVector[2]], err, false))
        return false;
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool UploadTaskChunks::validJsonOfField(size_t index,
                                        const std::string &fieldName,
                                        const Json::Value &pJson,
                                        std::string &err, bool isForCreation) {
  switch (index) {
  case 0:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 64) {
      err = "String length exceeds limit for the " + fieldName +
            " field (the maximum value is 64)";
      return false;
    }

    break;
  case 1:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isInt()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 2:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  default:
    err = "Internal error in the server";
    return false;
  }
  return true;
}
